// src/core/components/Liveline.vue
<script setup lang="ts">
import { ref, computed, shallowRef, watch } from 'vue'
import type { LivelineProps, Padding, DegenOptions, BadgeVariant, WindowOption } from '../types'
import { resolveTheme, resolveSeriesPalettes, SERIES_COLORS } from '../theme'
import { useLivelineEngine, type EngineConfig } from '../useLivelineEngine'

const props = withDefaults(defineProps<LivelineProps>(), {
  theme: 'dark',
  color: '#3b82f6',
  window: 30,
  grid: true,
  badge: true,
  momentum: true,
  fill: true,
  scrub: true,
  loading: false,
  paused: false,
  exaggerate: false,
  badgeTail: true,
  badgeVariant: 'default',
  showValue: false,
  valueMomentumColor: false,
  tooltipY: 14,
  tooltipOutline: true,
  cursor: 'crosshair',
  pulse: true,
  lerpSpeed: 0.08,
  seriesToggleCompact: false,
})

const emit = defineEmits<{
  (e: 'update:window', secs: number): void
  (e: 'hover', point: { time: number; value: number; x: number; y: number } | null): void
  (e: 'seriesToggle', id: string, visible: boolean): void
}>()

const canvasRef = ref<HTMLCanvasElement | null>(null)
const containerRef = ref<HTMLDivElement | null>(null)
const valueDisplayRef = ref<HTMLSpanElement | null>(null)

const defaultFormatValue = (v: number) => v.toFixed(2)
const defaultFormatTime = (t: number) => {
  const d = new Date(t * 1000)
  const h = d.getHours().toString().padStart(2, '0')
  const m = d.getMinutes().toString().padStart(2, '0')
  const s = d.getSeconds().toString().padStart(2, '0')
  return `${h}:${m}:${s}`
}

// Computed palette
const palette = computed(() => {
  const p = resolveTheme(props.color, props.theme)
  if (props.lineWidth != null) p.lineWidth = props.lineWidth
  return p
})

// Multi-series palettes
const seriesPalettes = computed(() => {
  if (!props.series || props.series.length === 0) return null
  return resolveSeriesPalettes(props.series, props.theme)
})

// Default padding
const defaultPadding = computed<Required<Padding>>(() => ({
  top: props.badge ? 40 : 20,
  right: props.grid ? 60 : 20,
  bottom: 40,
  left: 20,
}))

const resolvedPadding = computed<Required<Padding>>(() => ({
  top: props.padding?.top ?? defaultPadding.value.top,
  right: props.padding?.right ?? defaultPadding.value.right,
  bottom: props.padding?.bottom ?? defaultPadding.value.bottom,
  left: props.padding?.left ?? defaultPadding.value.left,
}))

// Degen options
const degenOptions = computed<DegenOptions | undefined>(() => {
  if (!props.degen) return undefined
  if (props.degen === true) return { scale: 1 }
  return props.degen
})

// Momentum resolved
const momentumOverride = computed(() => {
  if (typeof props.momentum === 'string') return props.momentum
  return undefined
})

const showMomentum = computed(() => {
  return props.momentum === true || typeof props.momentum === 'string'
})

// Hidden series
const hiddenSeriesIds = ref<Set<string>>(new Set())

// Multi-series config
const isMultiSeries = computed(() => {
  return props.series != null && props.series.length > 0
})

const multiSeriesConfig = computed(() => {
  if (!props.series || !seriesPalettes.value) return undefined
  return props.series.map((s, i) => ({
    id: s.id,
    data: s.data,
    value: s.value,
    palette: seriesPalettes.value!.get(s.id) ?? resolveTheme(s.color || SERIES_COLORS[i % SERIES_COLORS.length], props.theme),
    label: s.label,
  }))
})

// Engine config
const engineConfig = shallowRef<EngineConfig>({
  data: props.data,
  value: props.value,
  palette: palette.value,
  windowSecs: props.window,
  lerpSpeed: props.lerpSpeed,
  showGrid: props.grid,
  showBadge: props.badge,
  showMomentum: showMomentum.value,
  momentumOverride: momentumOverride.value,
  showFill: props.fill,
  referenceLine: props.referenceLine,
  formatValue: props.formatValue ?? defaultFormatValue,
  formatTime: props.formatTime ?? defaultFormatTime,
  padding: resolvedPadding.value,
  onHover: (point) => emit('hover', point),
  showPulse: props.pulse,
  scrub: props.scrub,
  exaggerate: props.exaggerate,
  degenOptions: degenOptions.value,
  badgeTail: props.badgeTail,
  badgeVariant: props.badgeVariant as BadgeVariant,
  tooltipY: props.tooltipY,
  tooltipOutline: props.tooltipOutline,
  valueMomentumColor: props.valueMomentumColor,
  valueDisplayRef: valueDisplayRef,
  orderbookData: props.orderbook,
  loading: props.loading,
  paused: props.paused,
  emptyText: props.emptyText,
  multiSeries: multiSeriesConfig.value,
  isMultiSeries: isMultiSeries.value,
  hiddenSeriesIds: hiddenSeriesIds.value,
})

// Watch all props and update config
watch(
  () => [
    props.data, props.value, props.color, props.theme, props.window,
    props.grid, props.badge, props.momentum, props.fill, props.referenceLine,
    props.formatValue, props.formatTime, props.padding, props.pulse, props.scrub,
    props.exaggerate, props.degen, props.badgeTail, props.badgeVariant,
    props.tooltipY, props.tooltipOutline, props.valueMomentumColor,
    props.orderbook, props.loading, props.paused, props.emptyText,
    props.series, props.lerpSpeed, props.lineWidth,
  ],
  () => {
    engineConfig.value = {
      data: props.data,
      value: props.value,
      palette: palette.value,
      windowSecs: props.window,
      lerpSpeed: props.lerpSpeed,
      showGrid: props.grid,
      showBadge: props.badge,
      showMomentum: showMomentum.value,
      momentumOverride: momentumOverride.value,
      showFill: props.fill,
      referenceLine: props.referenceLine,
      formatValue: props.formatValue ?? defaultFormatValue,
      formatTime: props.formatTime ?? defaultFormatTime,
      padding: resolvedPadding.value,
      onHover: (point) => emit('hover', point),
      showPulse: props.pulse,
      scrub: props.scrub,
      exaggerate: props.exaggerate,
      degenOptions: degenOptions.value,
      badgeTail: props.badgeTail,
      badgeVariant: props.badgeVariant as BadgeVariant,
      tooltipY: props.tooltipY,
      tooltipOutline: props.tooltipOutline,
      valueMomentumColor: props.valueMomentumColor,
      valueDisplayRef: valueDisplayRef,
      orderbookData: props.orderbook,
      loading: props.loading,
      paused: props.paused,
      emptyText: props.emptyText,
      multiSeries: multiSeriesConfig.value,
      isMultiSeries: isMultiSeries.value,
      hiddenSeriesIds: hiddenSeriesIds.value,
    }
  },
  { deep: true },
)

// Initialize engine
useLivelineEngine(canvasRef, containerRef, engineConfig)

// Window change handler
const activeWindowSecs = ref(props.window)
watch(() => props.window, (newVal) => {
  activeWindowSecs.value = newVal
})

function handleWindowChange(secs: number) {
  activeWindowSecs.value = secs
  emit('update:window', secs)
  if (props.onWindowChange) {
    props.onWindowChange(secs)
  }
}

// Series toggle handler
function toggleSeries(id: string) {
  const newSet = new Set(hiddenSeriesIds.value)
  if (newSet.has(id)) {
    newSet.delete(id)
    emit('seriesToggle', id, true)
    if (props.onSeriesToggle) props.onSeriesToggle(id, true)
  } else {
    newSet.add(id)
    emit('seriesToggle', id, false)
    if (props.onSeriesToggle) props.onSeriesToggle(id, false)
  }
  hiddenSeriesIds.value = newSet
}

const isDark = computed(() => props.theme === 'dark')
const showSeriesToggle = computed(() => props.series && props.series.length > 1)

const cursorStyle = computed(() => props.scrub ? props.cursor : 'default')
const activeColor = computed(() => isDark.value ? 'rgba(255,255,255,0.7)' : 'rgba(0,0,0,0.55)')
const inactiveColor = computed(() => isDark.value ? 'rgba(255,255,255,0.25)' : 'rgba(0,0,0,0.22)')

const hoveredWindowSecs = ref<number | null>(null)

const windowsContainerStyle = computed(() => {
  const style = props.windowStyle || 'default'
  if (style === 'rounded') {
    return {
      position: 'relative' as const,
      display: 'inline-flex' as const,
      gap: '2px',
      padding: '3px',
      borderRadius: '999px',
      background: isDark.value ? 'rgba(255, 255, 255, 0.03)' : 'rgba(0, 0, 0, 0.02)',
    }
  }

  if (style === 'text') {
    return {
      position: 'relative' as const,
      display: 'inline-flex' as const,
      gap: '4px',
      padding: '0',
      borderRadius: '6px',
      background: 'transparent',
    }
  }

  return {
    position: 'relative' as const,
    display: 'inline-flex' as const,
    gap: '2px',
    padding: '2px',
    borderRadius: '6px',
    background: isDark.value ? 'rgba(255, 255, 255, 0.03)' : 'rgba(0, 0, 0, 0.02)',
  }
})

function windowButtonStyle(w: WindowOption) {
  const isActive = w.secs === activeWindowSecs.value
  const isHovered = hoveredWindowSecs.value === w.secs
  return {
    position: 'relative' as const,
    zIndex: 1,
    fontSize: '11px',
    padding: (props.windowStyle || 'default') === 'text' ? '2px 6px' : '3px 10px',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    transition: 'color 0.2s',
    fontFamily: 'inherit',
    appearance: 'none' as const,
    WebkitAppearance: 'none' as const,
    margin: '0',
    color: isActive ? activeColor.value : inactiveColor.value,
    opacity: isHovered ? 0.8 : 1,
  }
}

function isSeriesHidden(id: string) {
  return hiddenSeriesIds.value.has(id)
}

function seriesToggleButtonStyle(id: string) {
  const hidden = isSeriesHidden(id)
  return {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    padding: '3px 8px',
    background: hidden
      ? 'transparent'
      : isDark.value
        ? 'rgba(255, 255, 255, 0.06)'
        : 'rgba(0, 0, 0, 0.035)',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    opacity: hidden ? 0.4 : 1,
    transition: 'opacity 0.2s, background 0.15s, color 0.2s',
    fontFamily: 'system-ui, -apple-system, sans-serif',
    fontSize: '11px',
    fontWeight: 500,
    lineHeight: '16px',
    appearance: 'none' as const,
    WebkitAppearance: 'none' as const,
    margin: '0',
    color: hidden
      ? isDark.value
        ? 'rgba(255, 255, 255, 0.25)'
        : 'rgba(0, 0, 0, 0.22)'
      : isDark.value
        ? 'rgba(255, 255, 255, 0.7)'
        : 'rgba(0, 0, 0, 0.55)',
  }
}

function seriesDotStyle(id: string, color: string) {
  return {
    display: 'inline-block',
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    flexShrink: 0,
    transition: 'opacity 0.2s',
    opacity: isSeriesHidden(id) ? 0.4 : 1,
    backgroundColor: color,
  }
}
</script>

<template>
  <div
    class="liveline-wrapper"
    :class="isDark ? 'dark' : 'light'"
    style="display: flex; flex-direction: column; width: 100%; height: 100%;"
  >
    <!-- Live value display -->
    <span
      v-if="showValue"
      ref="valueDisplayRef"
      class="liveline-value"
      style="display: block; font-size: 20px; font-weight: 500; font-family: 'SF Mono', Menlo, monospace; transition: color 0.3s; letter-spacing: -0.01em; margin-bottom: 8px; padding-top: 4px;"
      :style="{
        paddingLeft: `${resolvedPadding.left}px`,
        color: isDark ? 'rgba(255,255,255,0.85)' : '#111',
      }"
    />

    <!-- Control bars row -->
    <div
      v-if="(windows && windows.length > 0) || showSeriesToggle"
      class="liveline-controls"
      style="display: flex; align-items: center; gap: 6px; margin-bottom: 6px;"
      :style="{ marginLeft: `${resolvedPadding.left}px` }"
    >
      <!-- Time window controls -->
      <div
        v-if="windows && windows.length > 0"
        class="liveline-windows"
        :class="[windowStyle || 'default', isDark ? 'dark' : 'light']"
        :style="windowsContainerStyle"
      >
        <button
          v-for="w in windows"
          :key="w.secs"
          class="liveline-window-btn"
          :class="{ active: w.secs === activeWindowSecs }"
          :style="windowButtonStyle(w)"
          @mouseenter="hoveredWindowSecs = w.secs"
          @mouseleave="hoveredWindowSecs = null"
          @click="handleWindowChange(w.secs)"
        >
          {{ w.label }}
        </button>
      </div>

      <!-- Series toggle -->
      <div
        v-if="showSeriesToggle"
        class="liveline-series-toggle"
        style="display: flex; gap: 4px;"
      >
        <button
          v-for="s in series"
          :key="s.id"
          class="liveline-series-btn"
          :class="{ hidden: isSeriesHidden(s.id) }"
          :style="seriesToggleButtonStyle(s.id)"
          @click="toggleSeries(s.id)"
        >
          <span
            class="liveline-series-dot"
            :style="seriesDotStyle(s.id, s.color || SERIES_COLORS[series!.indexOf(s) % SERIES_COLORS.length])"
          />
          <span
            v-if="!seriesToggleCompact && s.label"
            class="liveline-series-label"
            style="font-size: 11px;"
          >
            {{ s.label }}
          </span>
        </button>
      </div>
    </div>

    <!-- Chart container -->
    <div
      ref="containerRef"
      class="liveline-container"
      style="position: relative; flex: 1; min-height: 0;"
      :style="{ cursor: cursorStyle }"
    >
      <canvas
        ref="canvasRef"
        style="display: block; width: 100%; height: 100%;"
      />
    </div>
  </div>
</template>

// demo/src/Liveline.tsx
import { useRef, useState, useLayoutEffect, useMemo, useCallback } from 'react'
import type { LivelineProps, Momentum, DegenOptions } from './types'
import { resolveTheme, resolveSeriesPalettes, SERIES_COLORS } from './theme'
import { useLivelineEngine } from './useLivelineEngine'

const defaultFormatValue = (v: number) => v.toFixed(2)

const defaultFormatTime = (t: number) => {
  const d = new Date(t * 1000)
  const h = d.getHours().toString().padStart(2, '0')
  const m = d.getMinutes().toString().padStart(2, '0')
  const s = d.getSeconds().toString().padStart(2, '0')
  return `${h}:${m}:${s}`
}

export function Liveline({
  data,
  value,
  series: seriesProp,
  theme = 'dark',
  color = '#3b82f6',
  window: windowSecs = 30,
  grid = true,
  badge = true,
  momentum = true,
  fill = true,
  scrub = true,
  loading = false,
  paused = false,
  emptyText,
  exaggerate = false,
  degen: degenProp,
  badgeTail = true,
  badgeVariant = 'default',
  showValue = false,
  valueMomentumColor = false,
  windows,
  onWindowChange,
  windowStyle,
  tooltipY = 14,
  tooltipOutline = true,
  orderbook,
  referenceLine,
  formatValue = defaultFormatValue,
  formatTime = defaultFormatTime,
  lerpSpeed = 0.08,
  padding: paddingOverride,
  onHover,
  cursor = 'crosshair',
  pulse = true,
  mode = 'line',
  candles,
  candleWidth,
  liveCandle,
  lineMode,
  lineData,
  lineValue,
  onModeChange,
  onSeriesToggle,
  seriesToggleCompact = false,
  lineWidth,
  className,
  style,
}: LivelineProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const containerRef = useRef<HTMLDivElement>(null)
  const valueDisplayRef = useRef<HTMLSpanElement>(null)
  const windowBarRef = useRef<HTMLDivElement>(null)
  const windowBtnRefs = useRef<Map<number, HTMLButtonElement>>(new Map())
  const [indicatorStyle, setIndicatorStyle] = useState<{ left: number; width: number } | null>(null)
  const modeBarRef = useRef<HTMLDivElement>(null)
  const modeBtnRefs = useRef<Map<string, HTMLButtonElement>>(new Map())
  const [modeIndicatorStyle, setModeIndicatorStyle] = useState<{ left: number; width: number } | null>(null)
  const [hiddenSeries, setHiddenSeries] = useState<Set<string>>(new Set())
  const lastSeriesPropRef = useRef(seriesProp)
  if (seriesProp && seriesProp.length > 0) lastSeriesPropRef.current = seriesProp

  const palette = useMemo(() => {
    const p = resolveTheme(color, theme)
    if (lineWidth != null) p.lineWidth = lineWidth
    return p
  }, [color, theme, lineWidth])
  const isDark = theme === 'dark'
  const isMultiSeries = seriesProp != null && seriesProp.length > 0
  const showSeriesToggle = (lastSeriesPropRef.current?.length ?? 0) > 1

  // Per-series palettes (memoized on series ids + colors + theme)
  const seriesPalettes = useMemo(() => {
    if (!seriesProp || seriesProp.length === 0) return null
    return resolveSeriesPalettes(seriesProp, theme)
  }, [seriesProp, theme])

  // Normalized multi-series config for the engine
  const multiSeries = useMemo(() => {
    if (!seriesProp || !seriesPalettes) return undefined
    return seriesProp.map((s, i) => ({
      id: s.id,
      data: s.data,
      value: s.value,
      palette: seriesPalettes.get(s.id) ?? resolveTheme(s.color || SERIES_COLORS[i % SERIES_COLORS.length], theme),
      label: s.label,
    }))
  }, [seriesProp, seriesPalettes, theme])

  // Resolve momentum prop: boolean enables auto-detect, string overrides
  const showMomentum = momentum !== false
  const momentumOverride: Momentum | undefined =
    typeof momentum === 'string' ? momentum : undefined

  const defaultRight = badge ? 80 : grid ? 54 : 12
  const pad = {
    top: paddingOverride?.top ?? 12,
    right: paddingOverride?.right ?? defaultRight,
    bottom: paddingOverride?.bottom ?? 28,
    left: paddingOverride?.left ?? 12,
  }

  // Degen mode: explicit prop wins
  const degenEnabled = degenProp != null
    ? degenProp !== false
    : false
  const degenOptions: DegenOptions | undefined = degenEnabled
    ? (typeof degenProp === 'object' ? degenProp : {})
    : undefined

  // Window buttons state
  const [activeWindowSecs, setActiveWindowSecs] = useState(
    windows && windows.length > 0 ? windows[0].secs : windowSecs
  )
  const effectiveWindowSecs = windows ? activeWindowSecs : windowSecs

  // Measure active window button for sliding indicator
  useLayoutEffect(() => {
    if (!windows || windows.length === 0) return
    const btn = windowBtnRefs.current.get(activeWindowSecs)
    const bar = windowBarRef.current
    if (btn && bar) {
      const barRect = bar.getBoundingClientRect()
      const btnRect = btn.getBoundingClientRect()
      setIndicatorStyle({
        left: btnRect.left - barRect.left,
        width: btnRect.width,
      })
    }
  }, [activeWindowSecs, windows])

  // Measure active mode button for sliding indicator
  const activeMode = lineMode ? 'line' : 'candle'
  useLayoutEffect(() => {
    if (!onModeChange) return
    const btn = modeBtnRefs.current.get(activeMode)
    const bar = modeBarRef.current
    if (btn && bar) {
      const barRect = bar.getBoundingClientRect()
      const btnRect = btn.getBoundingClientRect()
      setModeIndicatorStyle({
        left: btnRect.left - barRect.left,
        width: btnRect.width,
      })
    }
  }, [activeMode, onModeChange])

  // Series toggle handler — prevent hiding the last visible series
  const handleSeriesToggle = useCallback((id: string) => {
    setHiddenSeries(prev => {
      const next = new Set(prev)
      if (next.has(id)) {
        next.delete(id)
        onSeriesToggle?.(id, true)
      } else {
        // Count visible series — don't hide last one
        const totalSeries = seriesProp?.length ?? 0
        const visibleCount = totalSeries - next.size
        if (visibleCount <= 1) return prev
        next.add(id)
        onSeriesToggle?.(id, false)
      }
      return next
    })
  }, [seriesProp?.length, onSeriesToggle])

  const ws = windowStyle ?? 'default'

  useLivelineEngine(canvasRef, containerRef, {
    data,
    value,
    palette,
    windowSecs: effectiveWindowSecs,
    lerpSpeed,
    showGrid: grid,
    showBadge: isMultiSeries ? false : badge,
    showMomentum: isMultiSeries ? false : showMomentum,
    momentumOverride,
    showFill: isMultiSeries ? false : fill,
    referenceLine,
    formatValue,
    formatTime,
    padding: pad,
    onHover,
    showPulse: pulse,
    scrub,
    exaggerate,
    degenOptions: isMultiSeries ? undefined : degenOptions,
    badgeTail,
    badgeVariant,
    tooltipY,
    tooltipOutline,
    valueMomentumColor,
    valueDisplayRef: showValue ? valueDisplayRef : undefined,
    orderbookData: orderbook,
    loading,
    paused,
    emptyText,
    mode,
    candles,
    candleWidth,
    liveCandle,
    lineMode,
    lineData,
    lineValue,
    multiSeries,
    isMultiSeries,
    hiddenSeriesIds: hiddenSeries,
  })

  const cursorStyle = scrub ? cursor : 'default'

  const activeColor = isDark ? 'rgba(255,255,255,0.7)' : 'rgba(0,0,0,0.55)'
  const inactiveColor = isDark ? 'rgba(255,255,255,0.25)' : 'rgba(0,0,0,0.22)'

  return (
    <>
      {/* Live value display — above the chart */}
      {showValue && (
        <span
          ref={valueDisplayRef}
          style={{
            display: 'block',
            fontSize: 20,
            fontWeight: 500,
            fontFamily: '"SF Mono", Menlo, monospace',
            color: isDark ? 'rgba(255,255,255,0.85)' : '#111',
            transition: 'color 0.3s',
            letterSpacing: '-0.01em',
            marginBottom: 8,
            paddingTop: 4,
            paddingLeft: pad.left,
          }}
        />
      )}

      {/* Control bars row — window pills + mode toggle + series chips side by side */}
      {((windows && windows.length > 0) || onModeChange || showSeriesToggle) && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 6, marginLeft: pad.left }}>
          {/* Time window controls */}
          {windows && windows.length > 0 && (
            <div
              ref={windowBarRef}
              style={{
                position: 'relative',
                display: 'inline-flex',
                gap: ws === 'text' ? 4 : 2,
                background: ws === 'text' ? 'transparent'
                  : isDark ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.02)',
                borderRadius: ws === 'rounded' ? 999 : 6,
                padding: ws === 'text' ? 0 : ws === 'rounded' ? 3 : 2,
              }}
            >
              {/* Sliding indicator (default + rounded) */}
              {ws !== 'text' && indicatorStyle && (
                <div style={{
                  position: 'absolute',
                  top: ws === 'rounded' ? 3 : 2,
                  left: indicatorStyle.left,
                  width: indicatorStyle.width,
                  height: ws === 'rounded' ? 'calc(100% - 6px)' : 'calc(100% - 4px)',
                  background: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.035)',
                  borderRadius: ws === 'rounded' ? 999 : 4,
                  transition: 'left 0.25s cubic-bezier(0.4, 0, 0.2, 1), width 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
                  pointerEvents: 'none' as const,
                }} />
              )}
              {windows.map((w) => {
                const isActive = w.secs === activeWindowSecs
                return (
                  <button
                    key={w.secs}
                    ref={(el) => {
                      if (el) windowBtnRefs.current.set(w.secs, el)
                      else windowBtnRefs.current.delete(w.secs)
                    }}
                    onClick={() => {
                      setActiveWindowSecs(w.secs)
                      onWindowChange?.(w.secs)
                    }}
                    style={{
                      position: 'relative',
                      zIndex: 1,
                      fontSize: 11,
                      padding: ws === 'text' ? '2px 6px' : '3px 10px',
                      borderRadius: ws === 'rounded' ? 999 : 4,
                      border: 'none',
                      cursor: 'pointer',
                      fontFamily: 'system-ui, -apple-system, sans-serif',
                      fontWeight: isActive ? 600 : 400,
                      background: 'transparent',
                      color: isActive ? activeColor : inactiveColor,
                      transition: 'color 0.2s, background 0.15s',
                      lineHeight: '16px',
                    }}
                  >
                    {w.label}
                  </button>
                )
              })}
            </div>
          )}

          {/* Mode toggle — separate bar with its own sliding indicator */}
          {onModeChange && (
            <div
              ref={modeBarRef}
              style={{
                position: 'relative',
                display: 'inline-flex',
                gap: ws === 'text' ? 4 : 2,
                background: ws === 'text' ? 'transparent'
                  : isDark ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.02)',
                borderRadius: ws === 'rounded' ? 999 : 6,
                padding: ws === 'text' ? 0 : ws === 'rounded' ? 3 : 2,
              }}
            >
              {/* Sliding indicator */}
              {ws !== 'text' && modeIndicatorStyle && (
                <div style={{
                  position: 'absolute',
                  top: ws === 'rounded' ? 3 : 2,
                  left: modeIndicatorStyle.left,
                  width: modeIndicatorStyle.width,
                  height: ws === 'rounded' ? 'calc(100% - 6px)' : 'calc(100% - 4px)',
                  background: isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.035)',
                  borderRadius: ws === 'rounded' ? 999 : 4,
                  transition: 'left 0.25s cubic-bezier(0.4, 0, 0.2, 1), width 0.25s cubic-bezier(0.4, 0, 0.2, 1)',
                  pointerEvents: 'none' as const,
                }} />
              )}
              {/* Line icon */}
              <button
                ref={(el) => {
                  if (el) modeBtnRefs.current.set('line', el)
                  else modeBtnRefs.current.delete('line')
                }}
                onClick={() => onModeChange('line')}
                style={{
                  position: 'relative',
                  zIndex: 1,
                  padding: '5px 7px',
                  borderRadius: ws === 'rounded' ? 999 : 4,
                  border: 'none',
                  cursor: 'pointer',
                  background: 'transparent',
                  display: 'flex',
                  alignItems: 'center',
                }}
              >
                <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                  <path
                    d="M1 8.5C2.5 8.5 3 4 5.5 4S7.5 7 8.5 7C9.5 7 10 3.5 11 3.5"
                    stroke={activeMode === 'line' ? activeColor : inactiveColor}
                    strokeWidth={activeMode === 'line' ? 1.5 : 1.2}
                    strokeLinecap="round"
                    fill="none"
                  />
                </svg>
              </button>
              {/* Candle icon */}
              <button
                ref={(el) => {
                  if (el) modeBtnRefs.current.set('candle', el)
                  else modeBtnRefs.current.delete('candle')
                }}
                onClick={() => onModeChange('candle')}
                style={{
                  position: 'relative',
                  zIndex: 1,
                  padding: '5px 7px',
                  borderRadius: ws === 'rounded' ? 999 : 4,
                  border: 'none',
                  cursor: 'pointer',
                  background: 'transparent',
                  display: 'flex',
                  alignItems: 'center',
                }}
              >
                <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                  <line x1="3.5" y1="1" x2="3.5" y2="11"
                    stroke={activeMode === 'candle' ? activeColor : inactiveColor} strokeWidth="1" />
                  <rect x="2" y="3" width="3" height="5" rx="0.5"
                    fill={activeMode === 'candle' ? activeColor : inactiveColor} />
                  <line x1="8.5" y1="2" x2="8.5" y2="10"
                    stroke={activeMode === 'candle' ? activeColor : inactiveColor} strokeWidth="1" />
                  <rect x="7" y="4" width="3" height="4" rx="0.5"
                    fill={activeMode === 'candle' ? activeColor : inactiveColor} />
                </svg>
              </button>
            </div>
          )}

          {/* Series toggle chips */}
          {showSeriesToggle && (
            <div style={{
              display: 'inline-flex',
              gap: ws === 'text' ? 4 : 2,
              background: ws === 'text' ? 'transparent'
                : isDark ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.02)',
              borderRadius: ws === 'rounded' ? 999 : 6,
              padding: ws === 'text' ? 0 : ws === 'rounded' ? 3 : 2,
              opacity: isMultiSeries ? 1 : 0,
              transition: 'opacity 0.4s',
              pointerEvents: isMultiSeries ? 'auto' : 'none',
            }}>
              {(lastSeriesPropRef.current ?? []).map((s, si) => {
                const isHidden = hiddenSeries.has(s.id)
                const seriesColor = s.color || SERIES_COLORS[si % SERIES_COLORS.length]
                return (
                  <button
                    key={s.id}
                    onClick={() => handleSeriesToggle(s.id)}
                    style={{
                      position: 'relative',
                      zIndex: 1,
                      fontSize: 11,
                      padding: seriesToggleCompact
                        ? (ws === 'text' ? '2px 4px' : '5px 7px')
                        : (ws === 'text' ? '2px 6px' : '3px 8px'),
                      borderRadius: ws === 'rounded' ? 999 : 4,
                      border: 'none',
                      cursor: 'pointer',
                      fontFamily: 'system-ui, -apple-system, sans-serif',
                      fontWeight: 500,
                      background: isHidden ? 'transparent' : (ws === 'text' ? 'transparent' : (isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.035)')),
                      color: isHidden ? inactiveColor : activeColor,
                      opacity: isHidden ? 0.4 : 1,
                      transition: 'opacity 0.2s, background 0.15s, color 0.2s',
                      lineHeight: '16px',
                      display: 'flex',
                      alignItems: 'center',
                      gap: seriesToggleCompact ? 0 : 4,
                    }}
                  >
                    <span style={{
                      width: seriesToggleCompact ? 8 : 6,
                      height: seriesToggleCompact ? 8 : 6,
                      borderRadius: '50%',
                      background: seriesColor,
                      flexShrink: 0,
                      opacity: isHidden ? 0.4 : 1,
                      transition: 'opacity 0.2s',
                    }} />
                    {!seriesToggleCompact && (s.label ?? s.id)}
                  </button>
                )
              })}
            </div>
          )}
        </div>
      )}

      <div
        ref={containerRef}
        className={className}
        style={{
          width: '100%',
          height: '100%',
          position: 'relative',
          ...style,
        }}
      >
        <canvas
          ref={canvasRef}
          style={{ display: 'block', cursor: cursorStyle }}
        />
      </div>
    </>
  )
}
